apiVersion: v1
kind: Service
metadata:
  name: taski-backend
  namespace: taski
spec:
  selector:
    app: taski-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP