apiVersion: v1
kind: Service
metadata:
  name: taski-frontend
  namespace: taski
spec:
  selector:
    app: taski-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer